"""add chat

Revision ID: 89fcb819cb21
Revises: 97091a839941
Create Date: 2024-12-08 19:46:44.571466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fcb819cb21'
down_revision: Union[str, None] = '97091a839941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
